name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build and Deploy Documentation using MkDocs
        uses: Tangerine-Community/tangy-mkdocs-build-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          CUSTOM_DOMAIN: htdocs.dev
          MKDOCS_VERSION: 1.1.2